### ISSUE TITLE
Since 14.04, dropbox icon sometime disappears after the lock screen kicks in.

### ISSUE THREAD

**Issue by Rmano** [rgcjonas/gnome-shell-extension-appindicator#40] opened 2014-06-07 22:41 UTC
The title says it all. 
Sometime the dropbox icons disappears from the panel; I notice it after returning from lock screen. 
Disabling and enabling the extension has no effects, but restarting gnome-shell works. 
I have set the default for appindicator to show new icons in the panel, BTW. 

System: Ubuntu Gnome 14.04, gnome-shell 3.10.4, dropbox up-to-date. 

I understand there is really little data here; if someone can direct me in how to get more info next time it happens, I will try.

Thanks!

**Comment by flavioelawi** [comment] 2015-08-06 15:10
same problem in ubuntu 15.04, gnome 3.14, after the gdm unlock the appindicator disappear, but the applet are alive in background

**Comment by cyberalex4life** [comment] 2015-08-07 11:51
this kind of things happen to me in Gnome 3.16 Manjaro Linux too and I am not using the extension any more; so my guess is that this is more a Gnomish issue than a problem of this extension. I am using other extensions too, I am not sure what the problem is, I have not yet started  studying Gnome Shell, so I can't point my finger in any direction

PS: I am not the developer, nor a developer; I can't give you support with these bugs.

**Comment by rgcjonas** [comment] 2015-09-28 15:24
Dropbox started using its own bundled copy of Qt5 some time ago, which always uses the legacy systray protocol. Things should improve once this bundled copy is updated to at least Qt 5.5.

However, Qt5 doesn't correctly re-register the icon if the `StatusNotifierWatcher` disappears and then later appears again, e.g. whenever the extension is disabled and enabled again (which happens when entering/leaving the lock screen), or if the shell restarts for whatever reason.

KDE4 indicators also tend to behave buggy in these scenarios.

This needs to be resolved in Qt5 upstream, since there is no viable workaround here.

**Closed by rgcjonas** 2015-09-28 15:24 UTC
